services:
  migrate:
    image: alpine:latest
    container_name: volume-migrate
    command: cp /source/database.sqlite /new/
    volumes:
      - /tmp:/source
      - db-data:/new
volumes:
  db-data:
